version: '3.1'

services:
    nginx:
        container_name: nginx
        image: nginx:alpine
        volumes:
            - ./:/app
            - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
            - ./docker/nginx/conf.d:/etc/nginx/conf.d
            - ./docker/log:/var/log
            - ./docker/run/php:/var/run/php
        ports:
            - 8080:80
        restart: always
        depends_on:
            - php7.2
            - mysql
    php7.2:
        container_name: php-fpm7.2
        image: php:7.2.29-fpm-alpine
        volumes:
            - ./:/app
            - ./docker/log:/var/log
            - ./docker/run/php:/var/run/php
            - ./docker/php/www.conf:/usr/local/etc/php-fpm.d/www.conf
        restart: always
        depends_on:
            - mysql
    mysql:
        container_name: mysql
        image: mysql:5.7
        volumes:
            - ./docker/mysql:/var/lib/mysql
            - ./docker/log:/var/log
        restart: always
        ports:
            - 3307:3306
        environment:
            MYSQL_ROOT_PASSWORD: 'thispasswordisnotsecuresochangeit'

#volumes:
#  app: {}